### ISSUE TITLE
CI not working with tests

### ISSUE THREAD

**Issue by facusapienza21** [ODINN-SciML/Huginn.jl#27]
Currently `Huginn.jl` has implemented the same workflow that is working in `Sleipnir.jl` to run the tests automatically after every commit to main. However, in Huginn this is not working, and the problem seems to be comming from `PyCall`. Observing both stacktraces, we observe that in Huginn it seems that the conda environmnet is not properly set:

![Screen Shot 2023-08-08 at 11 02 48 AM](https://github.com/ODINN-SciML/Huginn.jl/assets/39526081/bf5eca6d-5433-415d-9f1c-a325177481e9)

This error does't not show in Sleipnir. The problem is probably coming from the fact that here Sleipnir is being installed and imported as a separate module. Here is something in the [PyCall documentation](https://github.com/JuliaPy/PyCall.jl) that may help find the solution. 

![Screen Shot 2023-08-08 at 11 04 35 AM](https://github.com/ODINN-SciML/Huginn.jl/assets/39526081/679f4b61-8d1a-4ae8-a60c-f31df993960b)

**Comment by JordiBolibar** [comment]
Is this fixed now? I think we basically repeated the same workflow of Sleipnir inside Huginn in order to to `pyimport` to all necessary Python packages? Ideally, it would be nice to fix this and clean up this repetition. 

To be seen if now that we do `@reexport using Sleipnir` this is fixed.

**Comment by JordiBolibar** [comment]
I think for now we have reached a suitable solution. We can always re-open this if it becomes a problem again.
