### ISSUE TITLE
Fetch Python environment from Sleipnir.jl for CI

### ISSUE THREAD

**Issue by JordiBolibar** [ODINN-SciML/Huginn.jl#6]
Right now we are duplicating the `environment.yml` file in each of the repos for the CI to have access to the Python environment. This is problematic, since any update to the Python environment will have to be extended to the 4 ODINN repositories. 

For that, we should update the CI to download (e.g. using `wget`) the `environment.yml` file from Sleipnir.jl's GitHub repo.

**Comment by facusapienza21** [comment]
I managed to sync files across repositories using the [repo-file-sync-action](https://github.com/marketplace/actions/repo-file-sync-action) with GH Actions. An example of how this work is illustrated in these two toy repositories: 
- [Origin repository](https://github.com/facusapienza21/Sync-example-origin). This will be `Sleipnir.jl` and we will sync the `environment.yml`
- [Destiantion repository](https://github.com/facusapienza21/Sync-example-destination): `Huginn.jl`, `Muninn.jl`, `ODINN.jl`
After implementing the action and configure the sync file with the details of the repository, the next step is to create a fined-grained token (ideally, using `ODINN-SciML` as the owner) and add it as a GH secret in the origin repository. After the setup of the GH credentials is done (this has to be updated every 90 days), a [Pull Request](https://github.com/facusapienza21/Sync-example-destination/pull/1) will be created in the destination repository. We can force the PR to be accepted, but I oppening a PR is actually the best posible workflow for this goal. 

What do you think @JordiBolibar ? I can directly implement this in `Sleipnir` and sync with all the required repositories.

**Comment by JordiBolibar** [comment]
Sounds good! The only annoying things seems the 90 day token renewal, which will require maintenance.

**Comment by facusapienza21** [comment]
Actually, I think you can manually configure the token to never expire. However, I am not sure about how good of a practice this is. The good news is that the new tokens in GH allow you to have a very fine-tune on the tokens, meaning that we can create a token JUST for sync the repositories we want and JUST with the necessary right to perform the sync action. In this way, we don't need to compromise any security of the repo by creating this token forever. Also, this will be kept secret in GH, so we will be safe. I can move forward with this @JordiBolibar and implement accross repositories.

**Comment by JordiBolibar** [comment]
OK, go for it!
